#!/usr/bin/env bash
# Script to transfer a file from local machine to a server using SCP

# Assigning more descriptive names to the arguments
PATH="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

if [ "$#" -lt 4 ]
then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit 1
	else
	    scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$PATH" "$USERNAME@$IP":~
	    fi
