#!/usr/bin/env bash
# A bash script that configures nginx to host an HTML page with "Hello world!"

# Update package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello world!" | sudo tee /var/www/html/index.html
sudo service nginx start
