#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Configure redirection
sudo sed -i '15i\\nlocation /redirect_me {\n    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
